### ISSUE TITLE
Integration test are failing 

### ISSUE THREAD

**Issue by nitin-vavdiya** [eclipse-tractusx/SSI-agent-lib#84]
### Current Behavior
Integration tests are failing, due to this, we can not deploy lib to maven/github packages

`./mvnw integration-test` givesbelow error:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.902 s <<< FAILURE! -- in org.eclipse.tractusx.ssi.lib.did.resolver.DidUniResolverIT
[ERROR] org.eclipse.tractusx.ssi.lib.did.resolver.DidUniResolverIT.shouldResolveValidDid -- Time elapsed: 0.077 s <<< ERROR!
org.eclipse.tractusx.ssi.lib.did.resolver.DidResolverException: Unexpected exception: java.lang.IllegalArgumentException
	at org.eclipse.tractusx.ssi.lib.did.resolver.DidUniResolver.resolve(DidUniResolver.java:97)
	at org.eclipse.tractusx.ssi.lib.did.resolver.DidUniResolverIT.shouldResolveValidDid(DidUniResolverIT.java:96)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalArgumentException: Invalid JsonLdObject: {"didDocument":{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1"],"id":"did:key:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6","verificationMethod":[{"id":"did:key:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6#z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6","type":"JsonWebKey2020","controller":"did:key:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6","publicKeyJwk":{"kty":"OKP","crv":"Ed25519","x":"FN5URrQRnKSaEjQvC8e6vpNGxivoocgPLgmzv_5JH2k"}}],"assertionMethod":["did:key:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6#z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6"],"authentication":["did:key:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6#z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6"],"capabilityInvocation":["did:key:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6#z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6"],"capabilityDelegation":["did:key:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6#z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6"]}}
	at org.eclipse.tractusx.ssi.lib.model.JsonLdObject.<init>(JsonLdObject.java:71)
	at org.eclipse.tractusx.ssi.lib.model.did.DidDocument.<init>(DidDocument.java:53)
	at org.eclipse.tractusx.ssi.lib.model.did.DidDocument.fromJson(DidDocument.java:104)
	at org.eclipse.tractusx.ssi.lib.did.resolver.DidUniResolver.resolve(DidUniResolver.java:92)
	... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "context" is null
	at org.eclipse.tractusx.ssi.lib.model.JsonLdObject.getContext(JsonLdObject.java:101)
	at org.eclipse.tractusx.ssi.lib.model.JsonLdObject.<init>(JsonLdObject.java:59)
	... 7 more

```

### Expected Behavior
All tests should be passed

### Steps To Reproduce
Checkout main branch and run `./mvnw install` or `./mvnw integration-test`

**Comment by nitin-vavdiya** [comment]
@borisrizov-zf 
Can you assign this issue to me?

**Comment by nitin-vavdiya** [comment]
Fixed with https://github.com/eclipse-tractusx/SSI-agent-lib/pull/85

**Comment by borisrizov-zf** [comment]
Why do we even use `did:key`? We are currently only implementing `did:web` or am I missing something?

**Comment by nitin-vavdiya** [comment]
I Think lib supports resolving did:key

@koptan Please correct if I am wrong here
